Update chessboard image generation and issue update workflow

diff --git a/.github/workflows/chess.yml b/.github/workflows/chess.yml
--- a/.github/workflows/chess.yml
+++ b/.github/workflows/chess.yml
@@ -23,12 +23,11 @@ jobs:
           python-version: "3.x"
           cache: "pip"
 
-      - name: Install Python dependencies
-        run: |
-          pip install -r scripts/requirements.txt
-
       - name: Generate Chessboard Image
         run: |
+          # Install dependencies
+          pip install -r scripts/requirements.txt
+
           # delete all other chessboard images
           rm images/chessboard*.png
 
@@ -40,6 +39,12 @@ jobs:
             echo "$line" >> $GITHUB_ENV
           done < <(grep -v '^#' .env)
 
+          # Check for MOVE_STATUS and exit if it's "invalid"
+          if [ "$MOVE_STATUS" = "invalid" ]; then
+            echo "Move is invalid, but continuing with the next steps."
+            exit 1
+          fi
+
           # rename file to chessboard.png + timestamp
           TIMESTAMP=-$(date +%s)
           mv images/chessboard.png images/chessboard$TIMESTAMP.png 
@@ -50,18 +55,37 @@ jobs:
           # add Filename to github_env
           echo "CHESSBOARD_FILENAME=images/chessboard$TIMESTAMP.png" >> $GITHUB_ENV
 
-      - name: Edit issue
+      - name: Update issue
+        if: ${{ env.MOVE_STATUS == 'valid' }}
         uses: actions/github-script@v7
         with:
           script: |
-            github.rest.issues.update({
+            const moveHistory = "${{ env.GAME_HISTORY }}".replace(/\.\s/g, ".&nbsp&nbsp").replace(/\|/g, "<br>")
+            const issueBody = `
+            ### Comment on this issue to make a move! It's ${{ env.WHICH_TURN }}'s turn to move.
+            > Move has to be in Standard Algebraic Notation ([SAN](https://www.chess.com/terms/chess-notation)) (e4, Bf4, exd5, Qxf7+, ...) <br>
+
+            <div>
+            <img src="https://raw.githubusercontent.com/thieleju/thieleju/main/${{ env.CHESSBOARD_FILENAME }}" \>
+            </div>
+
+            ### Valid moves for ${{ env.WHICH_TURN }}
+            > ${{ env.VALID_MOVES }}
+
+            <details>
+              <summary>Show Move History</summary><br>
+              ${moveHistory}
+            </details>
+            `
+            await github.rest.issues.update({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
-              body: "Comment on this issue to make a move!\n- Move has to be in [Standard Algebraic Notation (SAN)](https://www.chess.com/terms/chess-notation) (e4, Bf4, exd5, Qxf7+, ...)\n\n![chessboard](https://raw.githubusercontent.com/thieleju/thieleju/main/${{ env.CHESSBOARD_FILENAME }})\n\nIt's ${{ env.WHICH_TURN}}'s turn to move.\n\nValid moves: ${{ env.VALID_MOVES }}\n\n${{ env.GAME_HISTORY }}"
+              body: issueBody
             })
 
       - name: Update readme link and commit changes
+        if: ${{ env.MOVE_STATUS == 'valid' }}
         run: |
           git config --global user.email "actions@github.com"
           git config --global user.name "GitHub Actions"
@@ -70,12 +94,22 @@ jobs:
           git commit -m "🚀 Update chessboard image, fen and readme"
           git push origin HEAD
 
-      - name: Remove comment that triggered workflow
+      - name: React with ✅ for valid moves and ❌ for invalid moves
         uses: actions/github-script@v7
         with:
           script: |
-            github.rest.issues.deleteComment({
-              comment_id: "${{ github.event.comment.id }}",
-              owner: context.repo.owner,
-              repo: context.repo.repo
-            })
+            if (${env.MOVE_STATUS} == 'valid') {
+              await github.reactions.createForIssueComment({
+                comment_id: context.issue.comment_id,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                content: 'white_check_mark'
+              })
+            } else {
+              await github.reactions.createForIssueComment({
+                comment_id: context.issue.comment_id,
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                content: 'x'
+              })
+            }
